import {
  Blocks,
  Zap,
  FileCode,
  Terminal,
  Wind,
  Smartphone,
  Code2,
  Cpu,
  Database,
  Palette,
  Layout,
  Box,
  Globe,
} from "lucide-react";

export const CATEGORIES = [
  "All",
  "Web Dev",
  "Mobile",
  "Data Science",
  "Design",
  "DevOps",
];

export const MOCK_SKILLS = [
  {
    name: "React",
    slug: "react",
    category: "Web Dev",
    icon: <Blocks />,
    color: "#61DAFB",
  },
  {
    name: "Next.js",
    slug: "nextjs",
    category: "Web Dev",
    icon: <Zap />,
    color: "#FFFFFF",
  },
  {
    name: "TypeScript",
    slug: "typescript",
    category: "Web Dev",
    icon: <FileCode />,
    color: "#3178C6",
  },
  {
    name: "Node.js",
    slug: "node-js",
    category: "Web Dev",
    icon: <Terminal />,
    color: "#339933",
  },
  {
    name: "Tailwind CSS",
    slug: "tailwind-css",
    category: "Web Dev",
    icon: <Wind />,
    color: "#38B2AC",
  },
  {
    name: "SwiftUI",
    slug: "swiftui",
    category: "Mobile",
    icon: <Smartphone />,
    color: "#F05138",
  },
  {
    name: "Flutter",
    slug: "flutter",
    category: "Mobile",
    icon: <Smartphone />,
    color: "#02569B",
  },
  {
    name: "React Native",
    slug: "react-native",
    category: "Mobile",
    icon: <Smartphone />,
    color: "#61DAFB",
  },
  {
    name: "Python",
    slug: "python",
    category: "Data Science",
    icon: <Code2 />,
    color: "#3776AB",
  },
  {
    name: "TensorFlow",
    slug: "tensorflow",
    category: "Data Science",
    icon: <Cpu />,
    color: "#FF6F00",
  },
  {
    name: "Pandas",
    slug: "pandas",
    category: "Data Science",
    icon: <Database />,
    color: "#150458",
  },
  {
    name: "Figma",
    slug: "figma",
    category: "Design",
    icon: <Palette />,
    color: "#F24E1E",
  },
  {
    name: "UI Design",
    slug: "ui-design",
    category: "Design",
    icon: <Layout />,
    color: "#FF3366",
  },
  {
    name: "Docker",
    slug: "docker",
    category: "DevOps",
    icon: <Box />,
    color: "#2496ED",
  },
  {
    name: "Kubernetes",
    slug: "kubernetes",
    category: "DevOps",
    icon: <Globe />,
    color: "#326CE5",
  },
];
